# After adding merchants or indexes,
# 1. Need to update elastic search if there are new merchants, because
#    it will create new index for this merchant
# 2. Run app:update_merchants rake tasks to update all indices and merchants

# 2016 - 2017
ssense:
  code:               sse
  name:               ssense
  domain:             //www.ssense.com
  pager_css:          div.browsing-pagination ul.nav
  item_css:           div.browsing-product-list figure.browsing-product-item
  index_pages:
    - /en-ca/men
    - /en-ca/women
  ssl:                true

getoutside:
  code:               get
  name:               getoutside
  domain:             //www.getoutsideshoes.com
  ssl:                true
  pager_css:          div.pager > div.pages ol
  item_css:           ul.products-grid li.item
  index_pages:
    - /new-arrivals.html
    - /mens.html
    - /womens.html
    - /kid-s.html
    - /accessories.html
    - /sale.html

zara:
  code:               zar
  name:               zara
  domain:             //www.zara.com/ca/en
  ssl:                true
  pager_css:          ~
  item_css:           ul.product-list li.product
  index_pages:
    - /woman/new-in-c840002.html
    - /woman/new-in-c805003.html
    - /woman/best-sellers-c858027.html
    - /woman/outerwear/view-all-c733882.html
    - /woman/trench-coats-c749003.html
    - /woman/jackets-c269184.html
    - /woman/blazers-c756615.html
    - /woman/knitwear/view-all-c733910.html
    - /woman/dresses/view-all-c733885.html
    - /woman/jumpsuits-c663016.html
    - /woman/tops/view-all-c733890.html
    - /woman/t-shirts/view-all-c733912.html
    - /woman/trousers/view-all-c733898.html
    - /woman/jeans/view-all-c733918.html
    - /woman/skirts/view-all-c733908.html
    - /woman/shorts-c733903.html
    - /woman/sweatshirts-c733914.html
    - /woman/shoes/view-all-c734142.html
    - /woman/bags/view-all-c734144.html
    - /woman/accessories/view-all-c733915.html
    - /woman/swimwear-c764512.html
    - /woman/special-prices-c763514.html
    - /woman/suiting-time-c507505.html
    - /woman/faux-fur-luxe-c835053.html
    - /trf/new-in-c840006.html
    - /trf/outerwear-c665507.html
    - /trf/dresses/view-all-c965503.html
    - /trf/tops-c269211.html
    - /trf/t-shirts/view-all-c965048.html
    - /trf/knitwear-c695503.html
    - /trf/trousers-c269212.html
    - /trf/shorts-c734192.html
    - /trf/jeans-c271018.html
    - /trf/skirts-c269213.html
    - /trf/sweatshirts-c669532.html
    - /trf/shoes-c269216.html
    - /trf/bags-c269223.html
    - /trf/denim/view-all-c966004.html
    - /man/new-in-c744526.html
    - /man/best-sellers-c858034.html
    - /man/basics/view-all-c501501.html
    - /man/outerwear-c277002.html
    - /man/jackets/view-all-c758501.html
    - /man/blazers-c269232.html
    - /man/suits-c269233.html
    - /man/trousers/view-all-c733862.html
    - /man/shorts-c637013.html
    - /man/jeans-c269235.html
    - /man/shirts/view-all-c733865.html
    - /man/t-shirts/view-all-c733866.html
    - /man/polos-c493002.html
    - /man/sweatshirts-c309502.html
    - /man/sweaters-c269238.html
    - /man/shoes/view-all-c734091.html
    - /man/bags/view-all-c734090.html
    - /man/accessories/view-all-c733868.html
    - /man/socks-c637031.html
    - /man/underwear-c893583.html
    - /man/swimwear-c637012.html
    - /man/special-prices-c661502.html
    - /man/denim-essentials-c671070.html
    - /man/dark-collection-c856018.html

# july 2017
octobersveryown:
  code:               ovo
  name:               octobersveryown
  domain:             //ca.octobersveryown.com
  ssl:                true
  pager_css:          ~
  item_css:           main.main-content div.grid__item
  index_pages:
    - /collections/all

# july 2017
livestock:
  code:               ltk
  name:               livestock
  domain:             //www.deadstock.ca
  ssl:                true
  pager_css:          div.paginate
  item_css:           div.container.main.content div.products div.four.columns.thumbnail
  index_pages:
    - /collections/new-arrivals
    - /collections/footwear
    - /collections/apparel
    - /collections/accessories

# august 27, 2017
canada_goose:
  code:               goo
  name:               canada_goose
  domain:             //www.canadagoose.com
  ssl:                true
  pager_css:          ~
  item_css:           div#primary ul#search-result-items li div.product-tile
  index_pages:
    - /ca/en/shop/men
    - /ca/en/shop/women
    - /ca/en/shop/kids

arcteryx:
  code:               arc
  name:               arcteryx
  domain:             //arcteryx.com
  ssl:                true
  pager_css:          ~
  item_css:           div#divContent div.searchResult
  index_pages:
    - /ProductFind.aspx?country=ca&language=en&gender=Mens
    - /ProductFind.aspx?country=ca&language=en&gender=Womens

# september 2, 2017
adidas_canada:
  code:               add
  name:               adidas_canada
  domain:             //www.adidas.ca
  ssl:                true
  pager_css:          div.paging#top-pagination
  item_css:           div.product-tile div.hockeycard
  index_pages:
    - /en/men?grid=true
    - /en/women?grid=true
    - /en/kids?grid=true

# september 3, 2017
sporting_life:
  code:               slf
  name:               sporting_life
  domain:             //www.sportinglife.ca
  ssl:                true
  pager_css:          div.pagination
  item_css:           div.product-card
  index_pages:
    - /c/ladies-outdoor-alltype-jackets
    - /c/ladies-outdoor-sweaters-fleece
    - /c/ladies-outdoor-tops-tees
    - /c/ladies-outdoor-dresses-skirts
    - /c/ladies-outdoor-pants
    - /c/ladies-fashion-outdoor-type-shorts
    - /c/ladies-fashion-type-outerwear
    - /c/ladies-fashion-dresses-skirts
    - /c/basketball-shoe-type-mens
    - /c/casual-shoe-type-ladies
    - /c/casual-shoe-type-mens
    - /c/cleated-shoe-type-mens
    - /c/cleated-shoe-type-womens
    - /c/crosstraining-shoe-type-ladies
    - /c/crosstraining-shoe-type-mens
    - /c/cycle-shoe-type-men
    - /c/cycle-shoe-type-women
    - /c/equipment-watches
    - /c/fitness-accessory-type-yf-accessories
    - /c/flip-flops
    - /c/footwear-accessories-mens
    - /c/footwear-accessories-womens
    - /c/goggle-type-otg-adult-goggles
    - /c/golf-shoe-type-ladies
    - /c/golf-shoe-type-mens
    - /c/hiking-shoe-type-ladies
    - /c/hiking-shoe-type-mens
    - /c/indoor-shoe-type-ladies
    - /c/indoor-shoe-type-mens
    - /c/ladies-accessories-bags
    - /c/ladies-accessories-belts
    - /c/ladies-accessories-facemasks-balaclavas
    - /c/ladies-accessories-gloves-mitts
    - /c/ladies-accessories-hats
    - /c/ladies-accessories-misc
    - /c/ladies-accessories-scarfs-neckwarmers
    - /c/ladies-accessories-socks
    - /c/ladies-accessories-winter-hats-toques
    - /c/ladies-aerobicwear-type-ath-bra
    - /c/ladies-athletic-fitness-pants
    - /c/ladies-athletic-fitness-tops-tees
    - /c/ladies-athleticwear-type-outerwear
    - /c/ladies-athleticwear-type-po-hoodies
    - /c/ladies-athleticwear-type-shorts
    - /c/ladies-fashion-sweaters
    - /c/ladies-fashion-tops-blouses
    - /c/ladies-fashion-type-pants
    - /c/ladies-fashion-type-shorts
    - /c/ladies-golf-bottoms
    - /c/ladies-golf-dresses-skirts
    - /c/ladies-golf-shirts-tops
    - /c/ladies-golf-type-accessories
    - /c/ladies-golf-type-jackets
    - /c/ladies-running-pants-tights
    - /c/ladies-running-shorts
    - /c/ladies-running-sstops-singlets
    - /c/ladies-runningwear-type-jackets
    - /c/ladies-runningwear-type-lstops
    - /c/ladies-runningwear-type-sport-bras
    - /c/ladies-ski-long-underwear
    - /c/ladies-ski-pants
    - /c/ladies-ski-sweaters-fleece
    - /c/ladies-skiwear-insulayers
    - /c/ladies-skiwear-type-coats
    - /c/ladies-skiwear-type-jackets
    - /c/ladies-skiwear-type-vests
    - /c/ladies-snowboard-jackets-vests
    - /c/ladies-snowboard-type-tech-fleece
    - /c/ladies-snowboard-type-tech-pants
    - /c/ladies-sock-type-sport-socks
    - /c/ladies-surf-skate-dresses-skirts
    - /c/ladies-surf-skate-pants
    - /c/ladies-surf-skate-shorts
    - /c/ladies-surf-skate-sweaters
    - /c/ladies-surf-skate-tops-tees
    - /c/ladies-surf-skate-type-casual-jkts
    - /c/ladies-swimwear
    - /c/ladies-tennis-type-accessories
    - /c/ladies-tennis-type-bottoms
    - /c/ladies-tennis-type-dress
    - /c/ladies-tennis-type-jackets
    - /c/ladies-tennis-type-skirt
    - /c/ladies-tennis-type-tops
    - /c/ladies-yoga-aerobics-coverups
    - /c/ladies-yoga-aerobics-shorts
    - /c/ladies-yoga-aerobics-tights
    - /c/ladies-yoga-aerobics-tops-tees
    - /c/lifestyle-swim-equipment
    - /c/lifestyle-swim-mens
    - /c/mens-athletic-fitness-tops-tees
    - /c/mens-athleticwear-type-ath-jackets
    - /c/mens-athleticwear-type-ath-pants
    - /c/mens-athleticwear-type-ath-shorts
    - /c/mens-athleticwear-type-ath-swtp
    - /c/mens-fashion-bottoms
    - /c/mens-fashion-outdoor-type-shorts
    - /c/mens-fashion-type-outerwear
    - /c/mens-fashion-type-shorts
    - /c/mens-fashion-type-sweaters
    - /c/mens-fashion-type-tees
    - /c/mens-fashion-type-wovens
    - /c/mens-golf-shorts
    - /c/mens-golf-sweaters-vests
    - /c/mens-golf-type-pant
    - /c/mens-golf-type-shirt
    - /c/mens-outdoor-accessories-bags
    - /c/mens-outdoor-alltype-jackets
    - /c/mens-outdoor-pants
    - /c/mens-outdoor-sweaters-fleece
    - /c/mens-outdoor-tees
    - /c/mens-outdoor-tops
    - /c/mens-outdoor-vests
    - /c/mens-running-pants-tights
    - /c/mens-running-shorts-separates
    - /c/mens-running-sstops-singlets
    - /c/mens-runningwear-type-jackets
    - /c/mens-runningwear-type-lstops
    - /c/mens-ski-pants
    - /c/mens-skiwear-type-coats
    - /c/mens-skiwear-type-fleece
    - /c/mens-skiwear-type-insulayers
    - /c/mens-skiwear-type-jackets
    - /c/mens-skiwear-type-sweaters
    - /c/mens-skiwear-type-vests
    - /c/mens-snowboard-fleece-softshells
    - /c/mens-snowboard-jackets
    - /c/mens-snowboard-pants
    - /c/mens-sock-type-sport-socks
    - /c/mens-surf-skate-bottoms
    - /c/mens-surf-skate-hoodies-sweats
    - /c/mens-surf-skate-jackets-vests
    - /c/mens-surf-skate-type-shorts
    - /c/mens-surf-skate-type-tees
    - /c/mens-surf-skate-type-wovens
    - /c/mens-tennis-tops
    - /c/mens-tennis-type-jackets
    - /c/mens-tennis-type-shorts
    - /c/running-shoe-type-ladies
    - /c/running-shoe-type-mens
    - /c/sandals-shoe-type-ladies
    - /c/sandals-shoe-type-mens
    - /c/snowboard-boot-type-ladies-snowboard-bts
    - /c/snowboard-boot-type-mens-snowboard-bts
    - /c/sun-protection
    - /c/tennis-shoe-type-ladies
    - /c/tennis-shoe-type-mens
    - /c/walking-shoe-type-ladies
    - /c/walking-shoe-type-mens
    - /c/winter-helmet-type
    - /c/winter-helmet-type-adult-recreational
    - /c/winterboots-shoe-type-ladies
    - /c/winterboots-shoe-type-mens

# september 13, 2017
sephora_canada:
  code:               sph
  name:               sephora_canada
  domain:             //www.sephora.com
  ssl:                true
  pager_css:          ~
  item_css:           a.SkuItem
  index_pages:
    - /brand/list.jsp

# september 15, 2017
michael_kors_canada:
  code:               mkr
  name:               michael_kors_canada
  domain:             //www.michaelkors.ca
  ssl:                true
  pager_css:          ~
  item_css:           ~
  index_pages:
    - /
